# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import market_maker_pb2 as market__maker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in market_maker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketMakerIngestionServiceStub(object):
    """Service definition for market maker ingestion
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLastSequenceNumber = channel.unary_unary(
                '/market_maker.MarketMakerIngestionService/GetLastSequenceNumber',
                request_serializer=market__maker__pb2.SequenceNumberRequest.SerializeToString,
                response_deserializer=market__maker__pb2.SequenceNumberResponse.FromString,
                _registered_method=True)
        self.GetAllOrderbooks = channel.unary_unary(
                '/market_maker.MarketMakerIngestionService/GetAllOrderbooks',
                request_serializer=market__maker__pb2.GetAllOrderbooksRequest.SerializeToString,
                response_deserializer=market__maker__pb2.GetAllOrderbooksResponse.FromString,
                _registered_method=True)
        self.StreamQuotes = channel.stream_stream(
                '/market_maker.MarketMakerIngestionService/StreamQuotes',
                request_serializer=market__maker__pb2.MarketMakerQuote.SerializeToString,
                response_deserializer=market__maker__pb2.QuoteUpdate.FromString,
                _registered_method=True)
        self.StreamSwap = channel.stream_stream(
                '/market_maker.MarketMakerIngestionService/StreamSwap',
                request_serializer=market__maker__pb2.MarketMakerSwap.SerializeToString,
                response_deserializer=market__maker__pb2.SwapUpdate.FromString,
                _registered_method=True)


class MarketMakerIngestionServiceServicer(object):
    """Service definition for market maker ingestion
    """

    def GetLastSequenceNumber(self, request, context):
        """Get the last sequence number for a maker (for synchronization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllOrderbooks(self, request, context):
        """Get all orderbooks across all token pairs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuotes(self, request_iterator, context):
        """Stream quotes (bidirectional streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSwap(self, request_iterator, context):
        """Stream swaps (bidirectional streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketMakerIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLastSequenceNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLastSequenceNumber,
                    request_deserializer=market__maker__pb2.SequenceNumberRequest.FromString,
                    response_serializer=market__maker__pb2.SequenceNumberResponse.SerializeToString,
            ),
            'GetAllOrderbooks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllOrderbooks,
                    request_deserializer=market__maker__pb2.GetAllOrderbooksRequest.FromString,
                    response_serializer=market__maker__pb2.GetAllOrderbooksResponse.SerializeToString,
            ),
            'StreamQuotes': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamQuotes,
                    request_deserializer=market__maker__pb2.MarketMakerQuote.FromString,
                    response_serializer=market__maker__pb2.QuoteUpdate.SerializeToString,
            ),
            'StreamSwap': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSwap,
                    request_deserializer=market__maker__pb2.MarketMakerSwap.FromString,
                    response_serializer=market__maker__pb2.SwapUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'market_maker.MarketMakerIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('market_maker.MarketMakerIngestionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketMakerIngestionService(object):
    """Service definition for market maker ingestion
    """

    @staticmethod
    def GetLastSequenceNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_maker.MarketMakerIngestionService/GetLastSequenceNumber',
            market__maker__pb2.SequenceNumberRequest.SerializeToString,
            market__maker__pb2.SequenceNumberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllOrderbooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/market_maker.MarketMakerIngestionService/GetAllOrderbooks',
            market__maker__pb2.GetAllOrderbooksRequest.SerializeToString,
            market__maker__pb2.GetAllOrderbooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuotes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/market_maker.MarketMakerIngestionService/StreamQuotes',
            market__maker__pb2.MarketMakerQuote.SerializeToString,
            market__maker__pb2.QuoteUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSwap(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/market_maker.MarketMakerIngestionService/StreamSwap',
            market__maker__pb2.MarketMakerSwap.SerializeToString,
            market__maker__pb2.SwapUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
